version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200826
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
      - "4445:4445"
  chrome:
    image: selenium/node-chrome:3.141.59-20200826
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      #- SCREEN_WIDTH=1367
      #- SCREEN_HEIGHT=768
      #- SCREEN_DEPTH=24
      
  chrome2:
    image: selenium/node-chrome:3.141.59-20200826
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      #- SCREEN_WIDTH=1367
      #- SCREEN_HEIGHT=768
      #- SCREEN_DEPTH=24
      
#  chrome3:
#    image: selenium/node-chrome:3.141.59-20200826
#    volumes:
#      - /dev/shm:/dev/shm
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
#      - SCREEN_WIDTH=1367
#      - SCREEN_HEIGHT=768
#      - SCREEN_DEPTH=24

#  chrome4:
#    image: selenium/node-chrome:3.141.59-20200826
#    volumes:
#      - /dev/shm:/dev/shm
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
#      - SCREEN_WIDTH=1367
#      - SCREEN_HEIGHT=768
#      - SCREEN_DEPTH=24